vim.keymap.set("n", "<leader>xx", vim.cmd.TroubleToggle)
vim.keymap.set("n", "<leader>xw", function() vim.cmd.TroubleToggle('workspace_diagnostics') end)
vim.keymap.set("n", "<leader>xd", function() vim.cmd.TroubleToggle('document_diagnostics') end)
vim.keymap.set("n", "<leader>xl", function() vim.cmd.TroubleToggle('loclist') end)
vim.keymap.set("n", "<leader>xq", function() vim.cmd.TroubleToggle('quickfix') end)
vim.keymap.set("n", "<leader>xr", function() vim.cmd.TroubleToggle('lsp_references') end)
